Enable Kraken to insert the python version into files at build time
kraken-build/kraken-std pull request #108
Opened 2023-03-09 12:48 UTC by szgula

Add support for auto-updating of __version__ string in python source files 
(including: __init__.py, _version.py, __about__.py)

2023-03-09 15:25 UTC, NiklasRosenstein reviewed
One small inline comment. :)

Could you also create an integration test for this?

2023-03-09 15:25 UTC, NiklasRosenstein commented on src/kraken/std/python/buildsystem/poetry.py
> +from kraken.std.python.buildsystem.supporting_functions import update_python_version_str
nit: Maybe call it `helpers` or `util`?

2023-03-13 08:58 UTC, szgula commented on src/kraken/std/python/buildsystem/poetry.py
> +from kraken.std.python.buildsystem.supporting_functions import update_python_version_str
Done; also added integration test

2023-03-13 08:59 UTC, szgula commented on src/tests/integration/python/test_python.py
> +    # FIXME - now this is hardcoded also in .kraken.py file, find a way to pass it there from test level
@NiklasRosenstein any suggestions on this?

2023-03-13 09:15 UTC, cdbrkfxrpt approved these changes

2023-03-13 10:01 UTC, srstevenson requested changes

2023-03-13 10:01 UTC, srstevenson commented on src/kraken/std/python/buildsystem/helpers.py
> +        if not any(map(source_file_path.__contains__, FILENAMES)):
Would this be better expressed with logic such as `source_file_path.name in FILENAMES`?

2023-03-13 10:01 UTC, srstevenson commented on src/tests/integration/python/data/version-project/pyproject.toml
> +description = "Project for version upgrade check within Kraken-std integreation tests"
```suggestion
description = "Project for version upgrade check within Kraken-std integration tests"
```

2023-03-13 10:38 UTC, szgula commented on src/tests/integration/python/data/version-project/pyproject.toml
> +description = "Project for version upgrade check within Kraken-std integreation tests"
fixed

2023-03-13 10:38 UTC, szgula commented on src/kraken/std/python/buildsystem/helpers.py
> +        if not any(map(source_file_path.__contains__, FILENAMES)):
fixed

2023-03-13 10:38 UTC, szgula commented on src/kraken/std/python/buildsystem/helpers.py
> +    for source_file_path in glob.iglob(str(project_directory / "**/*.py"), recursive=True):
fixed

2023-03-15 19:46 UTC, NiklasRosenstein requested changes
Thanks a lot @szgula! This looks good! I've left a bunch of suggestions that I would like to cover before merging this. 🙂

2023-03-15 19:46 UTC, NiklasRosenstein commented on src/tests/integration/python/test_python.py
> +    # FIXME - now this is hardcoded also in .kraken.py file, find a way to pass it there from test level
As an alternative to placing a `.kraken.py` into that folder, you can build up the DAG inside the test. That would allow you to easily specify the build version number in the test.

```suggestion
    # FIXME - now this is hardcoded also in .kraken.py file, find a way to pass it there from test level
    pytest.build(as_version="9.9.9a1")
```

You can use `kraken.core.testing.kraken_project(kraken_ctx, tempdir)` for that and can forego the `kraken_ctx.load_project()` call.

2023-03-15 19:46 UTC, NiklasRosenstein commented on src/tests/integration/python/test_python.py
> +    # Check if project filenames before and after build are the same
```suggestion
    # Check if files that were supposed to be temporarily modified are the same after the build.
```

2023-03-15 19:46 UTC, NiklasRosenstein commented on src/tests/integration/python/test_python.py
> +    shutil.copytree(Path(__file__).parent / "data" / project_dir, tempdir / project_dir)
suggestion:

```suggestion
    shutil.copytree(original_dir, tempdir)
```

There's multiple copies of `Path(__file__).parent / "data" / project_dir` which would could just assign to a variable. Opting for `original_dir` here because `src_dir` could be confusing and sound like it's referring to a directory containing source code files.

You don't need to create a subdirectory inside the tempdir, so just using `tempdir` as the destination for the copy of the integration test directory is fine.

2023-03-15 19:46 UTC, NiklasRosenstein commented on src/tests/integration/python/test_python.py
> +            pytest.fail(".tar.gz file contains empty files")
I would suggest to use this more common notation:

```
assert init_file is not None, ".tar.gz file does not contain an '__init__.py'"
```

2023-03-15 19:46 UTC, NiklasRosenstein commented on src/tests/integration/python/test_python.py
> +    init_file_dir = "src/version_project/__init__.py"
```suggestion
    init_file = "src/version_project/__init__.py"
```

2023-03-16 14:36 UTC, szgula commented on .changelog/_unreleased.toml
> +description = "Enable Kraken to insert the project version into source files at build time"
done

2023-03-16 14:37 UTC, szgula commented on src/tests/integration/python/test_python.py
> +    init_file_dir = "src/version_project/__init__.py"
done

2023-03-16 14:42 UTC, szgula commented on src/tests/integration/python/test_python.py
> +    shutil.copytree(Path(__file__).parent / "data" / project_dir, tempdir / project_dir)
I replaced path with `original_dir`, 

for the `tempdir` I keep creating the additional folder layer - this way I can use same copy function as in other tests (`shutil.copytree` - which in python 3.7 and older does not support copy to existing folder, that is `dirs_exist_ok` flag)

2023-03-16 15:25 UTC, NiklasRosenstein commented on src/tests/integration/python/test_python.py
> +        python.settings.python_settings(project=loc_project, build_system=local_build_system)
Where these two lines necessary?

In the `.kraken.py` you only had the `python.build()` function call, and I _think_ it should be sufficient.

2023-03-16 15:26 UTC, NiklasRosenstein approved these changes
One more thread, otherwise LGTM 🚢

2023-03-16 15:55 UTC, szgula commented on src/tests/integration/python/test_python.py
> +        python.settings.python_settings(project=loc_project, build_system=local_build_system)
yeah, I was expecting this - but it was failing with "No build system found" message

2023-03-16 16:41 UTC, szgula commented on src/tests/integration/python/test_python.py
> +        python.settings.python_settings(project=loc_project, build_system=local_build_system)
can I assume that it's ok, resolve this and merge? :)

2023-03-16 22:25 UTC, merged