Comprehensive Global Gitignore File (non-fork)
kraken-build/kraken-std pull request #115
Opened 2023-03-15 10:05 UTC by LukeBax101

# Comprehensive Global Gitignore File

Ticket: https://helsing.atlassian.net/browse/ENGINFRA-667
RFC: https://helsing.atlassian.net/wiki/spaces/INF/pages/410256014/2023-02-09+Comprehensive+Global+Gitignore+File

# Action plan
## Chapter 1 - Cleanup
- [x] - Remove all deprecated functionality (add_paths, etc)
- [x] - Find out how other singleton tasks handle not being added multiple times
- [x] -  Remove task.create_check() and replace it with gitignore_check_task

## Chapter 2 - Apply

- [x] - GitignoreFile class, add
- [x] - generated_content instance property
- [x] - generated_content_token_list
- [x] - generated_content_hash 
- [x]    - refresh_gen_content: fn that receives tokens and fetches gitignore files from gitignore.io and stores them inside an instance variable
- [x]  - refresh_gen_content_hash: - everything between the guards is hashed including the token list
- [x]  - fn to validate the hash 
- [x]     - also compare the token list.
- [x]    - Extend parser to cover
- [x]        - generated_content
- [x]        - generated_content_token_list
- [x]        - generated_content_hash 
- [x] - Add a `tokens` parameter to the GitignoreSyncTask constructor (with the standard list as default paramter)
- [x] - Connect Apply task to GitignoreFile ...
- [x] - fix generation
- [x] - The apply fn should save a copy of the replaced file .gitignore.old

## Chapter 3 - Check
- [x] - Create dedicated gitignore_check_task
- [x] - Make sure __init__/gitignore adds the check task to the check group
- [x] - call gitignorefile.validate_hash() and return all TaskStatus variations
- [x] - compare tokens list

## Chapter 4 - Tidy up
- [x] - const file
- [x] - revisit \r with other write, read file
- [x] - parse_file, rename parse
- [x] - evaluate not inheriting from RenderFileTask
- [x] - check if RenderFileTask used to do any extra work (like creating a directory, etc)
- [x] - ensure check task validates gitignore sorting rules
- [x] - handle the exceptional case of not having an END_GUARD line (it crashes)

## Chapter 5 - After Feedback
- [x] - Figure out how to add missing previous entries that aren't covered by gitignore.io
- [ ] - Unit tests for the gitignore class
- [x] - Integration test for the task
- [x] - Final tidy up pass (imports etc.)

# kraken-std
- [x] Raise an exception if the task is added more than once
- [x] Add `extra_paths` parameter to manually extend the generated content
- [x] Analyse if we still need `Property[xxx]` in member vars (all task do, so yes)
- [x] Export `DEFAULT_TOKENS`

2023-03-15 14:33 UTC, cdbrkfxrpt requested changes

2023-03-15 14:33 UTC, cdbrkfxrpt commented on src/kraken/std/git/__init__.py
> +            GITIGNORE_TASK_NAME + ".check", GitignoreCheckTask, group="check", tokens=tokens, extra_paths=extra_paths
```suggestion
            f"{GITIGNORE_TASK_NAME}.check", GitignoreCheckTask, group="check", tokens=tokens, extra_paths=extra_paths
```

2023-03-15 14:33 UTC, cdbrkfxrpt commented on src/kraken/std/git/__init__.py
> +        raise ValueError("cannot gitignore task can only be added once")
```suggestion
        raise ValueError("cannot add gitignore task: task can only be added once")
```

2023-03-15 14:33 UTC, cdbrkfxrpt commented on src/kraken/std/git/gitignore.py
> +    def sort_gitignore(self, sort_paths: bool = True, sort_groups: bool = False) -> None:
do i understand correctly that this sorts entries in the gitignore file... alphabetically? if that's the case, what is the benefit of this vs simply taking what gitignore.io provides as-is?

2023-03-15 14:33 UTC, cdbrkfxrpt commented on src/kraken/std/git/tasks/gitignore_sync_task.py
> +        b) :attr:`extra_paths`: Additional required paths
if i'm understanding this correctly, we're giving the user a way to:

- add entries via the task
- add entries manually to the gitignore file

is that accurate? if so - i would _much_ prefer to only have one of these, ie letting the user add entries _only_ via manually editing the gitignore file - no `extra_paths`.

of course, we should have a "kraken internals" list of paths which get added, and these are ideally stored in the task so that in `kraken-hs`, we can inherit the task and extend the list, or some other implementation like that. would that be at all possible?

2023-03-15 15:45 UTC, LukeBax101 commented on src/kraken/std/git/tasks/gitignore_sync_task.py
> +        b) :attr:`extra_paths`: Additional required paths
Yes and no, at the minute the task is part of the `autoconf()` in `-hs` and so any extra paths are global across all hs projects (and thus are there to supplement the results from gitignore.io with some custom hs specific paths). I'm assuming (correct me if I'm wrong) that we want some level of per-project control of the `.gitignore` (in cases where a specific random file wants to be ignored without have repercussions for all other projects). The way I see it is we can achieve this in one of two ways: 
1. Have `-hs` extend the `-std` task with the hs specific paths and then have each project extend the `-hs` task and add it's own project specific paths (this would obviously mean the task could no longer live in `autoconf()` and would need to be called individually by each project). We could then block manually editing the `.gitignore`
2. Have `-hs` extend the `-std` task with the hs specific paths (called by default in every project in `autoconf()`) and then have the ability for each project to edit the `.gitignore` directly with project specific paths and have the check/apply task preserve these.

Hope that makes sense, happy to talk it over if that's easier

2023-03-15 15:46 UTC, dbuezas commented on src/kraken/std/git/gitignore.py
> +    def sort_gitignore(self, sort_paths: bool = True, sort_groups: bool = False) -> None:
It only sorts the "user" section. We kept this from the pre-existing task, it's IMO nicely done and convenient, it groups paths by using comments as separators and only sorts within them.
We don't touch the gitignore.io output

2023-03-15 15:49 UTC, dbuezas commented on src/kraken/std/git/tasks/gitignore_sync_task.py
> +        b) :attr:`extra_paths`: Additional required paths
The intent is that the final user will only add paths by writing them out of the guarded section.
We did though allow for passing both a list of tokens and some ad-hoc paths, and this is specifically made so that:
* kraken-hs can have a different token list
* kraken-hs can add a couple more paths (which also land inside the guarded section) which were already in use but not covered by gitignore.io. An good example are the files created by kraken itself.

2023-03-15 15:51 UTC, dbuezas commented on src/kraken/std/git/__init__.py
> +        raise ValueError("cannot gitignore task can only be added once")
no understands message the error? 😁

2023-03-15 21:08 UTC, NiklasRosenstein commented on src/kraken/std/git/gitignore.py
> +# If you need to define custom gitignore rules, add them below
I think it would make more sense if we supported custom rules at the top, because that's what people are most likely interested in seeing/editing most of the time.

2023-03-15 21:32 UTC, dbuezas commented on src/kraken/std/git/gitignore.py
> +# If you need to define custom gitignore rules, add them below
True, but this brings a limitation with it: paths can't be overridden by the user.

2023-03-15 22:32 UTC, NiklasRosenstein commented on src/kraken/std/git/gitignore.py
> +# If you need to define custom gitignore rules, add them below
That's a good point. Maybe support both? 🤔

2023-03-16 06:52 UTC, dbuezas commented on src/kraken/std/git/gitignore.py
> +# If you need to define custom gitignore rules, add them below
That would be ideal, do you see it as a must? 
I think it will delay the merge a bit, so I'll let @LukeBax101 continue the discussion :)

2023-03-16 08:24 UTC, cdbrkfxrpt commented on src/kraken/std/git/gitignore.py
> +    def sort_gitignore(self, sort_paths: bool = True, sort_groups: bool = False) -> None:
while i don't necessarily see the direct benefit for that in the context of "users edit the gitignore file by hand", i agree that it's kinda nice to have this - but then it should be documented! can you go ahead and add a task somewhere to add docs for how to deal with gitignore within Kraken please?

2023-03-16 09:03 UTC, cdbrkfxrpt commented on src/kraken/std/git/tasks/gitignore_sync_task.py
> +        b) :attr:`extra_paths`: Additional required paths
the baseline for this discussion is, imo: _kraken is a build orchestrator and should rely on common ecosystem processes where possible._ as such, i argue that manually editing the `.gitignore` file is the common process to deal with having git ignore certain things in a repository and we should therefore have the user make use of it.

in other words: kraken should be dealing _in gitignore.io-tokens and its own paths only_ when it comes to the `.gitignore` file. the task should **not** accept extra paths, since the user should be adding those manually to the `.gitignore` file, as is the common process. **in particular, the user should not be allowed to do both** - this is the path to maximum confusion.

people who add their own "opinion layer" to kraken (such as Helsing with kraken-hs) might want to make some additional paths defaulted in their `.gitignore` file. how they do that is ultimately up to them, but speaking for Helsing, kraken-hs could inherit the task generating the `.gitignore` file from kraken-std and extend the list of Kraken-specific paths to be added to the `.gitignore` file. so in a world where kraken-std has:

```python
class GitignoreSyncTask(Task):
    # ... other properties here
    kraken_paths = ["build"]  # instead of extra_paths
```

kraken-hs would have:

```python
from kraken.std.git import GitignoreSyncTask

class HsGitignoreSyncTask(GitignoreSyncTask):
    kraken_paths = [GitignoreSyncTask.kraken_paths, "hs-build", "other", "custom", "paths"]
```

this is of course just one idea of how to implement this and potentially not the most ergonomic one, but it hopefully makes clear what the concept i have in mind is (and perhaps also why i'm so insistent on this? :D)

2023-03-16 09:08 UTC, cdbrkfxrpt commented on src/kraken/std/git/gitignore.py
> +# If you need to define custom gitignore rules, add them below
i think supporting both has the potential to be confusing when people ~~haven't read~~ don't remember the docs, add their paths at the top and then wonder why their changes don't have any effect because they're overwritten in the generated section.

also, i would argue that the `.gitignore` file doesn't get edited all that much, so simplicity trumps having to jump to the bottom of the file. just let people add their stuff at the bottom - KISS.

2023-03-16 10:42 UTC, LukeBax101 commented on src/kraken/std/git/tasks/gitignore_sync_task.py
> +        b) :attr:`extra_paths`: Additional required paths
I've updated the MR to follow this new structure - please see `-hs` MR here: https://gitlab.helsing-dev.ai/infrastructure/kraken-hs/-/merge_requests/309/diffs for the hs specific extension and use of this

2023-03-16 11:41 UTC, cdbrkfxrpt approved these changes

2023-03-16 14:25 UTC, LukeBax101 commented on src/kraken/std/git/gitignore.py
> +    def sort_gitignore(self, sort_paths: bool = True, sort_groups: bool = False) -> None:
Docs describing this added in this MR: https://gitlab.helsing-dev.ai/infrastructure/kraken-hs/-/merge_requests/309/diffs

2023-03-16 14:38 UTC, merged