Implement a python.info task to get useful information about the virtual environment used by Kraken
kraken-build/kraken-std pull request #136
Opened 2023-04-18 11:39 UTC by callanoc

`kraken run python.info` currently returns a list of useful info, such as:

-  a path to the virtual environment used by kraken.
- Python version
- Python path

2023-04-18 19:40 UTC, ntrinquier requested changes

2023-04-18 19:40 UTC, ntrinquier commented on src/kraken/std/python/tasks/info_task.py
> +    return path
The python path which is interesting is the one that the managed environment uses (for debugging / development purposes), it's typically just in a subdir of the virtual environment (like `$VIRTUAL_ENV/bin/python`)

I think calling `which python` offers no guarantees regarding what it returns (it could be the system python, or anything else...)

```suggestion
    """Returns the path to the Python interpreter of the Kraken-managed environment."""
    return self.get_virtual_env_path() / "bin" / "python"
```

(+ moving it inside `InfoTask`)

2023-04-18 19:40 UTC, ntrinquier commented on src/kraken/std/python/tasks/info_task.py
> +    return run_command(["python", "--version"])
Similarly, we cannot expect `python` to be what we want, so we need to go through the managed environment:

```suggestion
    """Returns the version of the Python interpreter of the Kraken-managed environment."""
    return run_command([self.get_python_path(), "--version"])
```

2023-04-18 19:40 UTC, ntrinquier commented on src/kraken/std/python/tasks/info_task.py
> +            print(f"[WARNING]: current version is {version}, it should be 3.10, please check your python settings")
if we're talking about the version _of the managed environment_, we should not enforce any particular versions

2023-04-18 19:40 UTC, ntrinquier commented on src/kraken/std/python/tasks/info_task.py
> +    return subprocess.run(command, stdout=subprocess.PIPE, shell=False).stdout.decode("utf-8")
we should handle errors gracefully: for example, if the command returns a non-zero error code when we run "python --version", it is likely that we won't get the nice string (e.g. "3.10.0") that we expect, and the parsing will fail

so if the command returns an error, we should gracefully return `TaskStatus.failed(<some error>)` in the task, rather than letting the execution fails unpredictably

2023-04-18 19:40 UTC, ntrinquier commented on src/kraken/std/python/tasks/info_task.py
> +        """
```suggestion
        return "Displays metadata about the Kraken-managed environment."
```

2023-04-18 19:40 UTC, ntrinquier commented on src/kraken/std/python/tasks/info_task.py
> +        """
```suggestion
        "Displays metadata about the Kraken-managed environment."
```

2023-04-18 19:40 UTC, ntrinquier commented on src/kraken/std/python/tasks/info_task.py
> +        print(" ---------------------------------")
what does it look like? I think we could add some colours to make it nicer

2023-04-18 19:40 UTC, ntrinquier commented on src/kraken/std/python/tasks/info_task.py
> +        return path
let's just inline everything

```suggestion
        return self.build_system.get().get_managed_environment().get_path()
```

2023-04-18 19:40 UTC, ntrinquier commented on src/kraken/std/python/tasks/info_task.py
> +    This task depends on the python.install task as it creates the environment.
if would be cool if instead of having it as a comment, the task `python.info` task could actually depend on the `python.install` task

2023-04-19 13:11 UTC, NiklasRosenstein commented on src/kraken/std/python/tasks/info_task.py
> +    This task depends on the python.install task as it creates the environment.
I would actually argue that we may want to not have `info` depend on `install` as it may be unexpected that just giving info about the state of your Python environment actually installs it. One possible state of the Python environment is that it's not installed.

2023-04-19 13:13 UTC, NiklasRosenstein approved these changes
Added two more comments, but overall LGTM 👍

2023-04-19 13:13 UTC, NiklasRosenstein commented on src/kraken/std/python/tasks/info_task.py
> +        print(colored(" ---------- Kraken-managed environment information ----------", "magenta"))
Technically, the actual "thing" that manages the environment is Poetry or Slap. I would include that information here.

2023-04-19 15:35 UTC, merged