Add support for virtual Cargo workspaces
kraken-build/kraken-std pull request #39
Opened 2022-12-07 18:00 UTC by wngr

[`cargo metadata`](https://doc.rust-lang.org/cargo/commands/cargo-metadata.html) seems to give us all the necessary information, even for non-workspace Cargo projects.

Opening this as a draft, because I literally know the codebase only partially, and only for a couple of hours ..

2022-12-07 18:20 UTC, tetigi approved these changes
One nit, otherwise LGTM

2022-12-07 18:20 UTC, tetigi commented on src/kraken/std/cargo/manifest.py
> +            ["cargo", "metadata", "--format-version=1", "--manifest-path", str(projectDir.joinpath("Cargo.toml"))],
Isn't there a nice `projectDir / "Cargo.toml"` semantics you can use here?

2022-12-08 09:59 UTC, callumPearce commented
nit: change title to "Add support for **building** virtual Cargo Workspaces"

2022-12-09 15:04 UTC, merged

2022-12-09 15:04 UTC, NiklasRosenstein requested changes

2022-12-09 15:04 UTC, NiklasRosenstein commented on src/kraken/std/cargo/tasks/cargo_build_task.py
> +                filename = glob.glob(binOrLib.name + "*", root_dir=target_dir)  # type: ignore
I'm unsure what the type ignore is intended for; but I don't think it should be necessary.

Possibly because the `root_dir` argument was only added in Python 3.10? https://docs.python.org/3/library/glob.html

Maybe consider using `Path.glob()` instead: https://docs.python.org/3/library/pathlib.html#pathlib.Path.glob

Do I deduce correctly that the "hack to brute force copy multiple lib suffixes" is to cover all bases for the platform's different library suffixes (such as `.so`, `.dll`, or static library suffixes like `.a` and `.obj`)?

* Does this cover `lib*.a` on Linux? (I.e. will `Artifact.name` contain the `lib` prefix? Or does Rust not add a `lib` prefix?)
* The `CargoBinaryArtifact` is intended to represent executable binaries, so instead we may want to wrap library artifacts in a new `CargoLibraryArtifact`. 
  * Artifacts allow a more sophisticated consumption of artifacts produced by tasks.

2022-12-09 15:04 UTC, NiklasRosenstein commented
@tetigi Oh well, we passed each other by a few minutes 🤷

2022-12-09 15:05 UTC, tetigi commented
GAH Github pls. I accidentally merged this early. I'm sorry.

2022-12-09 15:06 UTC, tetigi commented
Will make a FLUP MR with the changes above.