Add update task to Poetry
kraken-build/kraken-std pull request #81
Opened 2023-01-27 19:47 UTC by rbyshko

2023-01-30 12:29 UTC, NiklasRosenstein commented
Btw this doesn't need to be blocked on https://github.com/kraken-build/kraken-core/pull/18 because the group is added automatically (but without description) like this as well.

2023-01-30 12:35 UTC, rbyshko commented
Ok, even better. I'd like to finish merging here. Do you have any comment regarding the implementation @NiklasRosenstein?

2023-01-30 21:04 UTC, NiklasRosenstein requested changes
One semantic change requested; the rest LGTM!

2023-01-30 21:04 UTC, NiklasRosenstein commented on src/kraken/std/python/buildsystem/slap.py
> +    def update_lockfile(self, settings: PythonSettings, pyproject: Pyproject) -> None:
Slap doesn't support lock files; even if we could use Poetry to produce it, it would not respect the lock file in any way. I would suggest that the `UpdateLockfileTask` would return `TaskStatus.skipped("not supported")` for Slap.

2023-02-03 13:05 UTC, rbyshko commented on src/kraken/std/python/buildsystem/slap.py
> +    def update_lockfile(self, settings: PythonSettings, pyproject: Pyproject) -> None:
Makes great sense! I added a commit that addresses your suggestion. Could you take a look please?

2023-02-03 14:58 UTC, merged